FROM {{ namespace }}/{{ image_prefix }}openstack-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block ec2_api_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.configure_user(name='ec2api') }}

ADD ec2-api-archive /ec2-api-source

{% set ec2_api_pip_packages = [
    '/ec2-api'
] %}

RUN ln -s ec2-api-source/* ec2-api \
    && {{ macros.install_pip(ec2_api_pip_packages | customizable("pip_packages")) }} \
    && mkdir -p /etc/ec2api \
    && cp -r /ec2-api/etc/ec2api/* /etc/ec2api \
    && chown -R ec2api: /etc/ec2api

COPY extend_start.sh /usr/local/bin/kolla_extend_start

RUN chmod 755 /usr/local/bin/kolla_extend_start

{% block ec2_api_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER ec2api
